### ISSUE TITLE
Change tab to space

### ISSUE THREAD

**Issue by cristofer-dev** [cristianrojas-dev/deliveryApp#13]
Creo que estabas usando TAB en lugar de SPACES:

Y precisamente por eso es que se sugiere siempre usar spaces, por que asi, un espacio es siempre un espacio en cualquier lado, en cambio los TAB cada entorno los mostrara según su sistema.

Para cambiar os TABS a spacios:

Al abrir el file, abajo aparece:
![captura de pantalla de 2018-03-21 09-12-16](https://user-images.githubusercontent.com/16719664/37710212-bb685d54-2ceb-11e8-83be-8476bbadfcac.png)

Le das click, y seleccionas **convertir sangrias a espacios**
![captura de pantalla de 2018-03-21 09-12-33](https://user-images.githubusercontent.com/16719664/37710207-b69ee612-2ceb-11e8-8c7c-1a9d7a8eb77b.png)

Eso cambiara todos los TABS por SPACES
![captura de pantalla de 2018-03-21 09-40-44](https://user-images.githubusercontent.com/16719664/37710378-382d6b18-2cec-11e8-8c96-9c552bc68ef2.png)

Con eso deberia estar Ready!

Hice 1 `commit` a `new_development` para probar, y todos los demas en una rama aparte, deje un PR para que veas los cambios y notes la diferencia entre TAB y spaces.

Al aceptar el pull request, no olvides eliminar la rama y cerrar este `issue`

**Comment by cristianrojas-dev** [comment]
buenísima, gracias!
